export const schema = gql`
  """
  Representation of ResourceLeave.
  """
  type ResourceLeave {
    "Description for id."
    id: String!

    "Description for description."
    description: String!

    "Description for from."
    from: DateTime!

    "Description for to."
    to: DateTime!

    "Description for firstDayWorkingHours."
    firstDayWorkingHours: Float!

    "Description for lastDayWorkingHours."
    lastDayWorkingHours: Float!

    "Description for resource."
    resource: Resource!

    "Description for resourceId."
    resourceId: String!

    "Description for createdAt."
    createdAt: DateTime!

    "Description for updatedAt."
    updatedAt: DateTime
  }

  """
  About queries
  """
  type Query {
    "Fetch ResourceLeaves."
    resourceLeaves: [ResourceLeave!]! @requireAuth

    "Fetch a ResourceLeave by id."
    resourceLeave(id: String!): ResourceLeave @requireAuth
  }

  """
  Autogenerated input type of InputResourceLeave.
  """
  input CreateResourceLeaveInput {
    "Description for description."
    description: String!

    "Description for from."
    from: DateTime!

    "Description for to."
    to: DateTime!

    "Description for firstDayWorkingHours."
    firstDayWorkingHours: Float!

    "Description for lastDayWorkingHours."
    lastDayWorkingHours: Float!

    "Description for resourceId."
    resourceId: String!
  }

  """
  Autogenerated input type of UpdateResourceLeave.
  """
  input UpdateResourceLeaveInput {
    "Description for description."
    description: String

    "Description for from."
    from: DateTime

    "Description for to."
    to: DateTime

    "Description for firstDayWorkingHours."
    firstDayWorkingHours: Float

    "Description for lastDayWorkingHours."
    lastDayWorkingHours: Float

    "Description for resourceId."
    resourceId: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new ResourceLeave."
    createResourceLeave(input: CreateResourceLeaveInput!): ResourceLeave!
      @requireAuth

    "Updates an existing ResourceLeave."
    updateResourceLeave(
      id: String!
      input: UpdateResourceLeaveInput!
    ): ResourceLeave! @requireAuth

    "Deletes an existing ResourceLeave."
    deleteResourceLeave(id: String!): ResourceLeave! @requireAuth
  }
`;
