export const schema = gql`
  """
  Representation of ResourceKind.
  """
  type ResourceKind {
    "Description for id."
    id: String!

    "Description for name."
    name: String!

    "Description for hourlyCost."
    hourlyCost: Float!

    "Description for Resources."
    Resources: [Resource]!

    "Description for workingHoursSchema."
    workingHoursSchema: WorkingHoursSchema!

    "Description for workingHoursSchemaId."
    workingHoursSchemaId: String!

    "Description for createdAt."
    createdAt: DateTime!

    "Description for updatedAt."
    updatedAt: DateTime
  }

  """
  About queries
  """
  type Query {
    "Fetch ResourceKinds."
    resourceKinds: [ResourceKind!]! @requireAuth

    "Fetch a ResourceKind by id."
    resourceKind(id: String!): ResourceKind @requireAuth
  }

  """
  Autogenerated input type of InputResourceKind.
  """
  input CreateResourceKindInput {
    "Description for name."
    name: String!

    "Description for hourlyCost."
    hourlyCost: Float!

    "Description for workingHoursSchemaId."
    workingHoursSchemaId: String!
  }

  """
  Autogenerated input type of UpdateResourceKind.
  """
  input UpdateResourceKindInput {
    "Description for name."
    name: String

    "Description for hourlyCost."
    hourlyCost: Float

    "Description for workingHoursSchemaId."
    workingHoursSchemaId: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new ResourceKind."
    createResourceKind(input: CreateResourceKindInput!): ResourceKind!
      @requireAuth

    "Updates an existing ResourceKind."
    updateResourceKind(
      id: String!
      input: UpdateResourceKindInput!
    ): ResourceKind! @requireAuth

    "Deletes an existing ResourceKind."
    deleteResourceKind(id: String!): ResourceKind! @requireAuth
  }
`;
