export const schema = gql`
  """
  Representation of ResourceAvailabilityOverride.
  """
  type ResourceAvailabilityOverride {
    "Description for id."
    id: String!

    "Description for description."
    description: String!

    "Description for dateFrom."
    dateFrom: DateTime

    "Description for dateTo."
    dateTo: DateTime

    "Description for dailyHoursAvailable."
    dailyHoursAvailable: Float!

    "Description for resources."
    resources: [Resource]!

    "Description for createdAt."
    createdAt: DateTime!

    "Description for updatedAt."
    updatedAt: DateTime
  }

  """
  About queries
  """
  type Query {
    "Fetch ResourceAvailabilityOverrides."
    resourceAvailabilityOverrides: [ResourceAvailabilityOverride!]! @requireAuth

    "Fetch a ResourceAvailabilityOverride by id."
    resourceAvailabilityOverride(id: String!): ResourceAvailabilityOverride
      @requireAuth
  }

  """
  Autogenerated input type of InputResourceAvailabilityOverride.
  """
  input CreateResourceAvailabilityOverrideInput {
    "Description for description."
    description: String!

    "Description for dateFrom."
    dateFrom: DateTime

    "Description for dateTo."
    dateTo: DateTime

    "Description for dailyHoursAvailable."
    dailyHoursAvailable: Float!
  }

  """
  Autogenerated input type of UpdateResourceAvailabilityOverride.
  """
  input UpdateResourceAvailabilityOverrideInput {
    "Description for description."
    description: String

    "Description for dateFrom."
    dateFrom: DateTime

    "Description for dateTo."
    dateTo: DateTime

    "Description for dailyHoursAvailable."
    dailyHoursAvailable: Float
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new ResourceAvailabilityOverride."
    createResourceAvailabilityOverride(
      input: CreateResourceAvailabilityOverrideInput!
    ): ResourceAvailabilityOverride! @requireAuth

    "Updates an existing ResourceAvailabilityOverride."
    updateResourceAvailabilityOverride(
      id: String!
      input: UpdateResourceAvailabilityOverrideInput!
    ): ResourceAvailabilityOverride! @requireAuth

    "Deletes an existing ResourceAvailabilityOverride."
    deleteResourceAvailabilityOverride(
      id: String!
    ): ResourceAvailabilityOverride! @requireAuth
  }
`;
