export const schema = gql`
  """
  Representation of ResourceCapability.
  """
  type ResourceCapability {
    "Description for id."
    id: String!

    "Description for name."
    name: String!

    "Description for resources."
    resources: [Resource]!

    "Description for createdAt."
    createdAt: DateTime!

    "Description for updatedAt."
    updatedAt: DateTime
  }

  """
  About queries
  """
  type Query {
    "Fetch ResourceCapabilities."
    resourceCapabilities: [ResourceCapability!]! @requireAuth

    "Fetch a ResourceCapability by id."
    resourceCapability(id: String!): ResourceCapability @requireAuth
  }

  """
  Autogenerated input type of InputResourceCapability.
  """
  input CreateResourceCapabilityInput {
    "Description for name."
    name: String!
  }

  """
  Autogenerated input type of UpdateResourceCapability.
  """
  input UpdateResourceCapabilityInput {
    "Description for name."
    name: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new ResourceCapability."
    createResourceCapability(
      input: CreateResourceCapabilityInput!
    ): ResourceCapability! @requireAuth

    "Updates an existing ResourceCapability."
    updateResourceCapability(
      id: String!
      input: UpdateResourceCapabilityInput!
    ): ResourceCapability! @requireAuth

    "Deletes an existing ResourceCapability."
    deleteResourceCapability(id: String!): ResourceCapability! @requireAuth
  }
`;
