export const schema = gql`
  """
  Representation of ResourceLeaveType.
  """
  type ResourceLeaveType {
    "Description for id."
    id: String!

    "Description for name."
    name: String!

    "Description for resourceLeaves."
    resourceLeaves: [ResourceLeave]!

    "Description for createdAt."
    createdAt: DateTime!

    "Description for updatedAt."
    updatedAt: DateTime!

    "Description for validForResourceKinds."
    validForResourceKinds: [ResourceKind]!
  }

  """
  About queries
  """
  type Query {
    "Fetch ResourceLeaveTypes."
    resourceLeaveTypes: [ResourceLeaveType!]! @requireAuth

    "Fetch a ResourceLeaveType by id."
    resourceLeaveType(id: String!): ResourceLeaveType @requireAuth
  }

  """
  Autogenerated input type of InputResourceLeaveType.
  """
  input CreateResourceLeaveTypeInput {
    "Description for name."
    name: String!
  }

  """
  Autogenerated input type of UpdateResourceLeaveType.
  """
  input UpdateResourceLeaveTypeInput {
    "Description for name."
    name: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new ResourceLeaveType."
    createResourceLeaveType(
      input: CreateResourceLeaveTypeInput!
    ): ResourceLeaveType! @requireAuth

    "Updates an existing ResourceLeaveType."
    updateResourceLeaveType(
      id: String!
      input: UpdateResourceLeaveTypeInput!
    ): ResourceLeaveType! @requireAuth

    "Deletes an existing ResourceLeaveType."
    deleteResourceLeaveType(id: String!): ResourceLeaveType! @requireAuth
  }
`;
